/*****************************************************************************
 * Copyright 2018 Francois Botha                                             *
 *                                                                           *
 * Licensed under the Apache License, Version 2.0 (the "License");           *
 * you may not use this file except in compliance with the License.          *
 * You may obtain a copy of the License at                                   *
 *                                                                           *
 *  http://www.apache.org/licenses/LICENSE-2.0                               *
 *                                                                           *
 * Unless required by applicable law or agreed to in writing, software       *
 * distributed under the License is distributed on an "AS IS" BASIS,         *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *
 * See the License for the specific language governing permissions and       *
 * limitations under the License.                                            *
 *                                                                           *
 *****************************************************************************/
package io.francoisbotha.bdgasadmin.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Setter
@ToString
@EqualsAndHashCode
@NoArgsConstructor
@DynamoDBTable(tableName = "bdgas_Task")
public class Task {

    private String id;
    private String taskType;
    private String taskCde;
    private String menuDesc;
    private String taskDesc;
    private String successDesc;
    private String templatePath;
    private String appName;
    private String classPath;


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getTaskType() {
        return taskType;
    }

    @DynamoDBAttribute
    public String getTaskCde() {
        return taskCde;
    }

    @DynamoDBAttribute
    public String getMenuDesc() {
        return menuDesc;
    }

    @DynamoDBAttribute
    public String getTaskDesc() {
        return taskDesc;
    }

    @DynamoDBAttribute
    public String getTemplatePath() {
        return templatePath;
    }

    @DynamoDBAttribute
    public String getAppName() {
        return appName;
    }

    @DynamoDBAttribute
    public String getClassPath() {
        return classPath;
    }

    @DynamoDBAttribute
    public String getSuccessDesc() {
        return successDesc;
    }

}
