/*****************************************************************************
 * Copyright 2018 Francois Botha                                             *
 *                                                                           *
 * Licensed under the Apache License, Version 2.0 (the "License");           *
 * you may not use this file except in compliance with the License.          *
 * You may obtain a copy of the License at                                   *
 *                                                                           *
 *  http://www.apache.org/licenses/LICENSE-2.0                               *
 *                                                                           *
 * Unless required by applicable law or agreed to in writing, software       *
 * distributed under the License is distributed on an "AS IS" BASIS,         *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *
 * See the License for the specific language governing permissions and       *
 * limitations under the License.                                            *
 *                                                                           *
 *****************************************************************************/
package io.francoisbotha.bdgasadmin.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.Arrays;
import java.util.List;

@Setter
@ToString
@EqualsAndHashCode
@NoArgsConstructor
@DynamoDBTable(tableName = "bdgas_WpLine")
public class WpLine  {

    private String id;
    private String wpId;
    private String taskId;
    private Integer lnNo;
    private String taskCde;
    private String taskDesc;
    private List<String> taskParams;
    private String lnResult;
    private String lnState;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getWpId() {
        return wpId;
    }

    @DynamoDBAttribute
    public String getTaskId() {
        return taskId;
    }

    @DynamoDBAttribute
    public Integer getLnNo() {
        return lnNo;
    }

    @DynamoDBAttribute
    public String getTaskCde() {
        return taskCde;
    }

    @DynamoDBAttribute
    public String getTaskDesc() {
        return taskDesc;
    }

    @DynamoDBAttribute
    public List<String> getTaskParams() {
        return taskParams;
    }

    @DynamoDBAttribute
    public String getLnResult() {
        return lnResult;
    }
//    public String getLnResult() {
//        return Arrays.copyOf(lnResult, lnResult.length);
//    }

    @DynamoDBAttribute
    public String getLnState() {
        return lnState;
    }

}
