/*****************************************************************************
 * Copyright 2018 Francois Botha                                             *
 *                                                                           *
 * Licensed under the Apache License, Version 2.0 (the "License");           *
 * you may not use this file except in compliance with the License.          *
 * You may obtain a copy of the License at                                   *
 *                                                                           *
 *  http://www.apache.org/licenses/LICENSE-2.0                               *
 *                                                                           *
 * Unless required by applicable law or agreed to in writing, software       *
 * distributed under the License is distributed on an "AS IS" BASIS,         *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  *
 * See the License for the specific language governing permissions and       *
 * limitations under the License.                                            *
 *                                                                           *
 *****************************************************************************/
package org.bdgas.adminservice.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.Arrays;

@Setter
@ToString
@EqualsAndHashCode
@NoArgsConstructor
@DynamoDBTable(tableName = "bdgas_Job")
public class Job {

    private String id;
    private String wpId;
    private String wpLineId;
    private String taskId;
    private String configAppName;
    private String configClassPath;
    private String configSync;
    private String configContext;
    private String configTimeout;
    private String sparkJobId;
    private String sparkStatus;
    private String sparkContext;
    private String jobStart;
    private String duration;
    private String result;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getWpId() {
        return wpId;
    }

    @DynamoDBAttribute
    public String getWpLineId() {
        return wpLineId;
    }

    @DynamoDBAttribute
    public String getTaskId() {
        return taskId;
    }

    @DynamoDBAttribute
    public String sparkJobId() {
        return sparkJobId;
    }

    @DynamoDBAttribute
    public String sparkStatus() {
        return sparkStatus;
    }

    @DynamoDBAttribute
    public String sparkContext() {
        return sparkContext;
    }

    @DynamoDBAttribute
    public String getJobStart() {
        return jobStart;
    }

    @DynamoDBAttribute
    public String getDuration() {
        return duration;
    }

    @DynamoDBAttribute
    public String getResult() {
        return result;
    }
//    public String[] getResult() {
//        return Arrays.copyOf(result, result.length);
//    }

}